#!/bin/sh

# Toggling the desktop-background causes the wallpaper to be redrawn.
/usr/bin/gsettings set org.gnome.gnome-flashback desktop-background false
/usr/bin/gsettings set org.gnome.gnome-flashback desktop-background true
